using Nop.Plugin.Synchronizers.WAPIOrders.Models.RegisterSale.Request;

namespace Nop.Plugin.Synchronizers.WAPIOrders.Models
{
    /// <summary>
    /// Represents the request made by the eCommerce to WAPI.
    /// </summary>
    public sealed class RegisterSaleRequest
    {
        /// <summary>
        /// Indicates the version of the eCommerce.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Indicates the name of the eCommerce.
        /// </summary>
        public string ECommerce { get; set; }

        /// <summary>
        /// Indicates the order id generated by the eCommerce.
        /// </summary>
        public string OrderNumber { get; set; }

        /// <summary>
        /// Indicates the datails of the sale order.
        /// </summary>
        public ORequest ORequest { get; set; }
    }
}
