using System.Collections.Generic;

namespace Nop.Plugin.Synchronizers.WAPIOrders.Models.RegisterSale.Response
{
    /// <summary>
    /// Represents the response of the register sale process.
    /// </summary>
    public sealed class OResponse
    {
        /// <summary>
        /// Indicates the order id generated by the eCommerce.
        /// </summary>
        public string OrderNumber { get; set; }

        /// <summary>
        /// Indicates the the status of the order.
        /// </summary>
        public string OrderStatus { get; set; }

        /// <summary>
        /// Indicates the unique code of the register transaction.
        /// </summary>
        public string TransactionCode { get; set; }

        /// <summary>
        /// Indicates the notes of the transaction.
        /// </summary>
        public string Notes { get; set; }

        /// <summary>
        /// Represents the frequent customer.
        /// </summary>
        public FShopper FShopper { get; set; }

        /// <summary>
        /// Represents the gift cards used in the transaction.
        /// </summary>
        public IList<Card> GCards { get; set; }

        /// <summary>
        /// Represents the credit payments methods used in the register sale process.
        /// </summary>
        public IList<Credit> ICredits { get; set; }
    }
}
